services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - type: bind
        source: .
        target: /home/vscode/workspaces
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]